### ISSUE TITLE
Sisters of Battle - Imagifier is Created with 2 Counts of Tale of the Warrior

### ISSUE THREAD

**Issue by GinFizzz** [TTSWarhammer40k/Battleforged-Workshop-Mod-Compilation#19]
Currently when a new Imagifier is added to the detachment, in my case a Battalion, there are 2 instances of Tale of the Warrior selected.

Once the number is adjusted down to one, it reverts to the checkbox option which is correct.

![javaw_tnUjNuR6Bj](https://user-images.githubusercontent.com/47032978/122626528-15c84a00-d079-11eb-9b38-0f40d334859c.png)

**Comment by Malice-red** [comment]
This is battleforge, not battle-scribe, report issues to their github https://github.com/BSData/wh40k/issues
