### ISSUE TITLE
"IMPORTANT - How to use maps!.txt" has broken link

### ISSUE THREAD

**Issue by TehGreatFred** [TTSWarhammer40k/Battleforged-Workshop-Mod-Compilation#24]
Issue File: https://github.com/TTSWarhammer40k/Battleforged-Workshop-Mod-Compilation/blob/master/IMPORTANT%20-%20How%20to%20use%20maps!.txt
https://steamcommunity.com/sharedfiles/filedetails/?id=1717042451 gives following error: 
```
Sorry!
An error was encountered while processing your request:

There was a problem accessing the item. Please try again.
```
Steps to reproduce:
1. Open the link

**Comment by Malice-red** [comment]
Updated the old readme file with the new link
