### ISSUE TITLE
Drukhari Raider (and Ravager) size too large

### ISSUE THREAD

**Issue by charlesamor** [TTSWarhammer40k/Battleforged-Workshop-Mod-Compilation#25]
Drukhari Raiders are an incorrect size and significantly larger than tabletop.  Drukhari Raiders are located in Warhammer 40k, Army Collections, Xenos Armies, Aeldari, Drukhari MMZ Complete Collection.  

Raiders in real life are approximately 7.5" long by 2.5" wide.  

Raiders in the collection have a variety of sizes.   
The brown old style raiders are 8.4" x 2.8" wide.   
The new style raiders are 8.7" x 3.2" wide.  There are also raider variants with extra bits that are too long.  
Ravagers are similarly scaled too large (and use the same IRL measurements as Raiders).  
It's visually noticeable that the collection raiders are 12-16% longer in each dimension than IRL raiders.  

I would like for the size of raiders to be scaled down appropriately to IRL.  I believe 5 clicks of the TTS scale tool does it.  
(I currently scale them myself for casual TTS play, but I am in a tournament that uses the Battleforged-Workshop-Mod-Compilation as the only official source for models.  So any size changes for the tournament have to be accepted through here.)

**Comment by Malice-red** [comment]
Fixed with todays update
