### ISSUE TITLE
Sorry not really an issue, its more of a Question

### ISSUE THREAD

**Issue by UlfMitHand** [TTSWarhammer40k/Battleforged-Workshop-Mod-Compilation#28]
In Kill Team\Factions\Chaos\Thousand Sons are three Tzaanfor Hornbearer models. All of them will toogle on the line tool while you grab the model and switch back to Grab tool once you put it down. Is there anyway anybody could scrap the code for that script? so i can copy paste it on other figures? (i can't code at all sorry) 

It would be awesome, if someone could help me with that.

**Comment by Malice-red** [comment]
Should be able to right click the models in question, and find the line measurement option and turn it off.
