### ISSUE TITLE
GSC new Board - Missing object, and invalid image format

### ISSUE THREAD

**Issue by KitsuneAkaiyuki** [TTSWarhammer40k/Battleforged-Workshop-Mod-Compilation#32]
okay, so! I've found a couple issues on the new Genestealer Cult board, missing object, and some invalid image formats on the following

Ridge Runner w/ Heavy Mortar is missing a passenger, and maybe part of it's base
Neophyte w/ Shotgun, the image of the shotgun appears to be missing/invalid format, as it's just kinda of a gray silvery blob
![missing obj](https://user-images.githubusercontent.com/102726472/161017964-f0eb8eb6-91a0-453c-879c-ab73711bfa57.png)
![unsupported format](https://user-images.githubusercontent.com/102726472/161017976-ce6854be-e48f-4578-9f77-652779f0ef1b.png)

**Comment by Malice-red** [comment]
First issue was caused because the original author removed an upload that this model was using. We may have a potential fix for this in the future.

**Comment by Malice-red** [comment]
Fix has been implemented and will this should be fixed by the next patch.
