### ISSUE TITLE
Ad Mech models not loading

### ISSUE THREAD

**Issue by Captainmikou** [TTSWarhammer40k/Battleforged-Workshop-Mod-Compilation#36]
Hello :)

so I just discovered that some models (like Belisarius Cawl) are not loading in the game. Is it something on my side or a bug ?
Please find pictures enclosed to illustrate the issue.

Thanking you in advance :)

![1](https://user-images.githubusercontent.com/106236402/170228735-db177f66-1db5-4b11-bd6d-c07dbcfb08f7.png)
![2](https://user-images.githubusercontent.com/106236402/170228740-6c5cf35e-b7aa-459d-b78f-8d97767c78b1.png)

**Comment by Malice-red** [comment]
Hello Captainmikou,

Are you using the latest update of battleforge when you try to load these models in?

**Comment by Captainmikou** [comment]
Hello Malice-red,

thanks a lot for your answer ! I took the time yesterday to install and download everything new and now it seems like it is working :).

I am therefore closing the problem.
