### ISSUE TITLE
Installer Link on Readme leads to a 404

### ISSUE THREAD

**Issue by HendrikDanker** [TTSWarhammer40k/Battleforged-Workshop-Mod-Compilation#4]
The [Direct Download[ Button here (https://github.com/TTSWarhammer40k/Battleforged-Workshop-Mod-Compilation/blob/master) leads to a 404
![](https://i.imgur.com/Pu6AOCe.png)

**Comment by Malice-red** [comment]
There is no self installer at the time of writing this response. Self-installer is a placeholder link.
