### ISSUE TITLE
Linux manual installation

### ISSUE THREAD

**Issue by Maze-fr** [TTSWarhammer40k/Battleforged-Workshop-Mod-Compilation#6]
Hello,

What a bad surprise when I found out that the manual installation instructions were only existing for Windows and Mac... (as if everybody enjoys paying for an OS ;-) )
As I am suing Linux (Xubuntu 20.10, to be precise), here is what I did...

I search for a "Tabletop Simulator" folder containing the "Saves" folder, and here it is : `~/.local/share/Tabletop Simulator`
Then what's left to do is the same as others.

It works like a charm !
Great job, fellows !

**Comment by Malice-red** [comment]
Instructions implemented into the readme for linux, should be good to go for now, cheers!
